### ISSUE TITLE
fatal error: yolo_v2_class.hpp: No such file or directory 

### ISSUE THREAD

**Issue by vaibhawkhemka** [robocomp/dsr-graph#49] opened 2021-06-30 18:46 UTC
[](url)
![yolo_error](https://user-images.githubusercontent.com/46538042/124014371-0fcf5300-da01-11eb-84a7-15e0795319ff.png)

Getting this error after running the command "make" in yolov4-tracker.
Any solution? @pbustos @JuanCarlosgg @orensbruli

**Comment by JuanCarlosgg** [comment] 2021-07-18 08:41
Have you installed darknet following the steps here? https://github.com/robocomp/dsr-graph/tree/development/components/yolov4-tracker#installation 

If so, are you able to compile other agents that use yolo like yolov4-detector?

**Comment by vaibhawkhemka** [comment] 2021-07-18 09:18
Hi @JuanCarlosgg ,
Yes, I have installed darknet according to steps mentioned except I have set GPU=0 in Makefile as my system doesn't have GPU. But , I think error is not related with GPU. 
And getting the same error with other agents as well that use yolo like yolov4-tracker.
What's your thought on this??

**Comment by JuanCarlosgg** [comment] 2021-07-18 09:33
Can you check if darknet is installed in /home/robocomp/software/darknet/ or in /home/robocomp/darknet/? 
In cmake it searches for the library in the first path, which differs from the installation instructions.

**Comment by vaibhawkhemka** [comment] 2021-07-18 09:56
@JuanCarlosgg I have checked with both cases i.e /home/robocomp/software/darknet/ and also in /home/robocomp/darknet/.

**Comment by JuanCarlosgg** [comment] 2021-07-18 10:54
Hello. 

I have done a clean install of darknet to try to replicate the error. I used the yolov4-detector agent as a test as the yolov4-tracker agent is not in use at the moment and I think it needs some changes to work.  

Everything works correctly if you move the darknet folder to software/ with the command  ```mv /home/robocomp/darknet/  /home/robocomp/software/```.  Another tried option is to modify the darknet path in lines 23 and 24 of src/CMakeListsSpecific.txt to the installation path.

**Comment by vaibhawkhemka** [comment] 2021-07-18 12:55
@JuanCarlosgg I have done the changes as suggested. As a Result ,Previous error has gone but a new error has popped up as shown below :
![error](https://user-images.githubusercontent.com/46538042/126067823-1743e8ff-5d7e-4e92-ae72-db6a4cbfb19b.jpg)

**Comment by DarkGeekMS** [comment] 2021-07-18 14:42
@vaibhawkhemka 
I remember getting the same error, due to incompatible g++ (gcc) version.
What version are you using ?

**Comment by vaibhawkhemka** [comment] 2021-07-18 15:23
@DarkGeekMS  I am using gcc-10 and g++ -10 version

**Comment by vaibhawkhemka** [comment] 2021-07-18 15:27
@DarkGeekMS @JuanCarlosgg  The Error is resolved when I switched to gcc-8 version. Thanks 
But a new error popped up as shown below:
![error2](https://user-images.githubusercontent.com/46538042/126072937-1989a716-fdb6-46ee-becd-03ec05ab3205.jpg)

**Comment by JuanCarlosgg** [comment] 2021-07-18 15:51
It is necessary to use gcc 10 to compile it because we use some features of c++20 that are available from that version.

This error https://github.com/robocomp/dsr-graph/issues/49#issuecomment-882052420 should be fixed by setting the -fno-char8_t option in the cmake compile flags.  This is defined in the src/CMakeListSpecific.txt file of the agents in the add_definitions command (line 23 in yolov4-detector).

If the command does not appear in your file you probably have an outdated version of the repository. If it does appear in the file you may not have regenerated the cmake files.

**Comment by vaibhawkhemka** [comment] 2021-07-19 12:10
@JuanCarlosgg  It worked. Thanks.
But getting a new error "/usr/bin/ld: cannot find -ldarknet"
![erro3](https://user-images.githubusercontent.com/46538042/126157731-4989386c-86e4-4d3e-bcd8-798810311e54.png)

**Comment by JuanCarlosgg** [comment] 2021-07-19 19:12
From the error it seems that the darknet .so file is not found. Check if it is in the /home/robocomp/software/darknet folder and if not, compile darknet again.

**Comment by vaibhawkhemka** [comment] 2021-07-20 04:49
@JuanCarlosgg darknet .so file is not found even after compiling darknet again and giving outputs as follows after compiling darknet:
![y1](https://user-images.githubusercontent.com/46538042/126263350-2e76b785-c388-409d-aa3f-03f71ced5ee7.png)
![y2](https://user-images.githubusercontent.com/46538042/126263359-07805a45-cf8a-423f-985b-bf638bea1b7a.png)
![y3](https://user-images.githubusercontent.com/46538042/126263363-3ca3ac7e-60f7-4674-8802-d483ff3c5e3d.png)
![y4](https://user-images.githubusercontent.com/46538042/126263366-abee196f-ca7e-4339-a5f5-95ac4fde7672.png)

Same issue is mentioned in [cannot find ldarknet](https://github.com/AlexeyAB/darknet/issues/1791), but unable to incorporate these changes. Hope u could help.

**Comment by JuanCarlosgg** [comment] 2021-07-20 06:59
The command "-L/home/robocomp/software/darknet -ldarknet" on line 24 in the src/CMakeListsSpecific.txt file should be enough for it to find the lib, so I'm not sure what's happening.

Can you paste the result of the commands:  ``` locate libdarknet.so  ```,  ``` ls /home/robocomp/software/darknet ``` and the content of the file src/CMakeListsSpecific.txt.

**Comment by vaibhawkhemka** [comment] 2021-07-20 09:10
@JuanCarlosgg  `locate libdarknet.so` doesn't give any output.
`ls /home/robocomp/software/darknet` output as follows :
![ls](https://user-images.githubusercontent.com/46538042/126294396-46a19e85-dd29-4380-9c51-d38108cfe0b2.png)

content of  file src/CMakeListsSpecific.txt. :
![cmake](https://user-images.githubusercontent.com/46538042/126294495-c0891b8b-5ad2-45ff-b218-e2e68ef642a2.png)

**Comment by JuanCarlosgg** [comment] 2021-07-20 09:35
It looks like the libdarknet.so file is not in the folder. Check if the file exists in the darknet/build directory. If it exist, copy it to the darknet folder. If it does not, try to compile darknet again and if it gives a compile error, paste the message here.

**Comment by vaibhawkhemka** [comment] 2021-07-20 10:41
@JuanCarlosgg libdarknet.so file is not present in darknet/build directory and compiling darknet again gives the same error.
![e](https://user-images.githubusercontent.com/46538042/126310645-530884cc-5bd5-4515-b245-dfdf26c2fd6d.png)

**Comment by JuanCarlosgg** [comment] 2021-07-20 10:48
So the problem is in the darknet compilation. Create a pastebin or a gist with the contents of the darknet Makefile and with the content of the file generated by the command  ``` make &> output.txt ```.

**Comment by vaibhawkhemka** [comment] 2021-07-20 12:00
@JuanCarlosgg Is there any other component in dsr-graph except graspDSR and yolo components that is in good shape and working?? As I need to test any component to understand the code.

**Comment by JuanCarlosgg** [comment] 2021-07-20 16:32
As you are not able to compile the agents that use Yolo you can try the navigation agents. All of them work properly (path_planner_astar, path_follower, elastic_band, mission_controller_viriato and a few more). You can also use the change_graph agent, which allows to inspect and modify the content of the graph, but this one behaves somewhat differently from normal agents.

In most cases you need to run ViriatoPyrep, idserver and viriatoDSR alongside your agents. Here you have access to a small tutorial to run DSR (https://github.com/robocomp/robocomp/blob/development/doc/DSR-start.md#dsrs-hello-world).

**Comment by vaibhawkhemka** [comment] 2021-07-21 05:44
@JuanCarlosgg  path_follower component is working but please explain how to use it like how the position of robot is changing/updating as I can't see any change in user interface.
![path_follower](https://user-images.githubusercontent.com/46538042/126437245-a89f8daf-aba6-4204-a56d-527c03e5c1b0.png)

**Comment by JuanCarlosgg** [comment] 2021-07-21 06:08
The navigation agents perform specific tasks. path_follower is only responsible for following a path generated by another agent. For the robot to move you must also execute path_planner_astar. In the 2D view of this agent you can select a point with right click and will generate a path for path_follower to start moving the robot.

**Comment by vaibhawkhemka** [comment] 2021-07-21 06:36
@JuanCarlosgg  ViriatoPyrep and ideserver is working fine but viriatoDSR is giving an error while compiling using current dsr-graph repo.
![viriato](https://user-images.githubusercontent.com/46538042/126442513-6b47f399-178f-41ce-a220-25ce83cb6704.png)

**Comment by JuanCarlosgg** [comment] 2021-07-21 06:50
Pull the latest changes from the robocomp repository and recompile and install DSR.

```
cd ~/robocomp
git pull
cd build
cmake .. -DDSR=TRUE
make -j$(nproc)
sudo make install
sudo ldconfig
```

Then do a clean compilation of the agents you need to run.

**Comment by vaibhawkhemka** [comment] 2021-07-21 07:48
@JuanCarlosgg  It Worked. Thanks a lot

**Closed as completed** 2021-10-21 11:25 UTC
